global using DevExpress.Maui;
global using DevExpress.Maui.Core;
global using Microsoft.Maui;
global using Microsoft.Maui.Controls.Compatibility;
global using Microsoft.Maui.Controls.Compatibility.Hosting;
global using Microsoft.Maui.Controls.Hosting;
global using Microsoft.Maui.Hosting;
global using Newtonsoft.Json;
global using MoviesKatta.Models;
global using Maui.Apps.Framework.MVVM;
global using MoviesKatta.IServices;
global using Maui.Apps.Framework.UI;
global using Grid = Microsoft.Maui.Controls.Grid;
global using Microsoft.Maui.LifecycleEvents;
global using MoviesKatta.ViewModels.Base;
global using MoviesKatta.Helpers;
global using MoviesKatta.ViewModels;
global using MoviesKatta.Views.Base;